#!/bin/sh
# POSIX method for converting hexadecimal notation to bytes
hex() {
	for i; do
		printf "\\$(printf %o $(( 0x$i )))"
	done
}

# Legacy magic bytes for SLP
# ref: https://wiki.vg/Server_List_Ping
hex fe 01 fa |
	# Server address and port
	nc "${1:-127.0.0.1}" "${2:-25565}" |
	# Skip the magic bytes
	dd bs=1 skip=10 2>/dev/null |
	# tr is one of the only POSIX utilities that
	# handles null bytes correctly
	tr '\0' '\n' | {
		printf 'Protocol version: '
		set "Minecraft server version" "Message of the day" "Current player count" "Max players"
	
		while IFS= read -r line; do
			if [ -n "$line" ]; then
				printf %s "$line"
			else
				printf '\n%s: ' "$1"
				shift
				# Discard extra empty line
				read -r _
			fi
		done
	
		printf '\n'
	}
